# Generated by Django 4.1.5 on 2023-01-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Населенный пункт')),
                ('leader', models.CharField(default='', max_length=255, verbose_name='Глава')),
                ('number_of_inhabitants', models.IntegerField(default=0, verbose_name='Количество жителей')),
                ('budget', models.IntegerField(default=0, verbose_name='Бюджет')),
                ('spending', models.IntegerField(blank=True, default=0, null=True, verbose_name='Расходы')),
                ('deficit', models.IntegerField(blank=True, default=0, null=True, verbose_name='Дефицит')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
            },
        ),
    ]
