# Generated by Django 4.1.5 on 2023-01-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localities',
            name='deficit',
            field=models.IntegerField(default=0, verbose_name='Дефицит'),
        ),
        migrations.AlterField(
            model_name='localities',
            name='spending',
            field=models.IntegerField(default=0, verbose_name='Расходы'),
        ),
    ]
