# Generated by Django 4.1.5 on 2023-01-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_localities_deficit_alter_localities_spending'),
    ]

    operations = [
        migrations.AddField(
            model_name='localities',
            name='img_link',
            field=models.TextField(default='https://www.emetechnologies.com/blog/cse/images/python-web-framework-django.jpg', verbose_name='Ссылка на картинку'),
        ),
    ]
