# Generated by Django 4.1.5 on 2023-01-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_localities_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localities',
            name='number_of_inhabitants',
            field=models.IntegerField(default=0, verbose_name='Население'),
        ),
    ]
